AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Compute resources.

Globals:
  Function:
    Tracing: Active
  Api:
    TracingEnabled: true
    # Setting this prevent the creation of "Stage" stage in AWS::Serverless::Api
    OpenApiVersion: "2.0"

Resources:
  # --- HTTP APIs ---
  ApiGatewayApiHttp:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod

  # --- Serverless Application Model (SAM) ---
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - arm64
      Events:
        GetGraphql:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApiHttp
            Path: /graphql
            Method: GET
        PostGraphql:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApiHttp
            Path: /graphql
            Method: POST
      PackageType: Image
    # For building the image for the `PackageType: Image` config
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./
      DockerTag: v3
