AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Compute resources.

Parameters:
  LambdaFunctionImageUri:
    Type: String

Resources:
  # --- CloudWatch ---
  LogsLogGroupHttpApiAccessLog:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub ${AWS::StackName}HttpApiAccessLog
      RetentionInDays: 30

  # --- HTTP APIs ---
  ApiGatewayApiHttp:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub ${AWS::StackName}ApiGatewayApiHttp
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - "*"
        AllowHeaders:
          - "*"
        ExposeHeaders:
          - "*"

  # --- HTTP APIs stage ---
  ApiGatewayStageHttpDefault:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref ApiGatewayApiHttp
      StageName: $default
      AutoDeploy: true
      DefaultRouteSettings:
        DetailedMetricsEnabled: true
      AccessLogSettings:
        DestinationArn: !GetAtt LogsLogGroupHttpApiAccessLog.Arn
        Format: >
          {"requestId": "$context.requestId", "ip": "$context.identity.sourceIp", "caller": "$context.identity.caller", "user": "$context.identity.user", "requestTime": "$context.requestTime", "routeKey": "$context.routeKey", "status": "$context.status"}

  # --- HTTP APIs route: POST /graphql ---
  ApiGatewayRoutePostGraphql:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiGatewayApiHttp
      RouteKey: "POST /graphql"
      Target: !Join ["/", [integrations, !Ref ApiGatewayIntegrationPostGraphql]]
  ApiGatewayIntegrationPostGraphql:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ApiGatewayApiHttp
      IntegrationMethod: POST
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt LambdaFunction.Arn
      PayloadFormatVersion: "2.0"

  # --- HTTP APIs route: GET /graphql ---
  ApiGatewayRouteGetGraphql:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiGatewayApiHttp
      RouteKey: "GET /graphql"
      Target: !Join ["/", [integrations, !Ref ApiGatewayIntegrationGetGraphql]]
  ApiGatewayIntegrationGetGraphql:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ApiGatewayApiHttp
      IntegrationMethod: GET
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt LambdaFunction.Arn
      PayloadFormatVersion: "2.0"

  # --- Serverless Application Model (SAM) ---
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - arm64
      PackageType: Image
      ImageUri: !Ref LambdaFunctionImageUri
      Tracing: Active
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
